import type { VehicleInfo, DiscoverCard, UserProfile } from './types';

export const mockVehicle: VehicleInfo = {
  name: 'Honda VEZEL',
  grade: 'e:HEV Z',
  image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?w=800&h=500&fit=crop',
  contractStartDate: '2025-04-01',
  monthlyPayment: 38500,
  currentMonthMileage: 342,
  totalMileage: 12480,
  color: 'プレミアムサンライトホワイト・パール',
};

export const mockProfile: UserProfile = {
  name: '田中',
  familySize: 4,
  hasChildren: true,
  prefecture: '神奈川県',
  interests: ['ドライブ', 'グルメ', 'アウトドア', '温泉'],
};

export const mockDiscoverCards: DiscoverCard[] = [
  {
    id: 'd1',
    title: '三浦半島ぐるっとドライブ',
    summary: '海沿いの絶景ルートを巡る日帰りドライブ。新鮮な海鮮ランチと城ヶ島の絶景を楽しめます。',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    category: 'drive',
    source: 'AI提案',
    isRead: false,
    isNew: true,
    createdAt: '2026-02-14',
    season: 'all',
    estimatedDriveTime: '約2時間30分',
    estimatedDistance: '約80km',
    details: '三浦半島を海沿いに巡るドライブコース。出発は横須賀から、海岸線に沿って走る爽快なルートです。途中、葉山マリーナで休憩、三崎港で新鮮なマグロ丼のランチ、城ヶ島で散策を楽しめます。お子様連れにもぴったりの、のんびりとしたドライブプランです。\n\n【おすすめスポット】\n・葉山マリーナ - おしゃれなカフェでひと休み\n・三崎港 - 本場のマグロ料理を堪能\n・城ヶ島 - 雄大な太平洋の景色\n・ソレイユの丘 - お子様が楽しめる花畑と遊具',
    tags: ['海', '絶景', 'グルメ', '家族向け'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd2',
    title: '箱根の隠れ家カフェ巡り',
    summary: '温泉街の裏路地にある知る人ぞ知るカフェを巡る、大人のドライブプラン。足湯も楽しめます。',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop',
    category: 'gourmet',
    source: 'AI提案',
    isRead: false,
    isNew: true,
    createdAt: '2026-02-13',
    season: 'winter',
    estimatedDriveTime: '約1時間30分',
    estimatedDistance: '約65km',
    details: '箱根の温泉街に点在する隠れ家カフェを巡るプラン。小涌谷の森の中にあるログハウスカフェ、強羅の和モダンな甘味処、仙石原のガラス張りのカフェなど、それぞれ個性的な空間でこだわりのコーヒーやスイーツを楽しめます。合間に無料の足湯スポットで身体を温めるのもおすすめです。',
    tags: ['カフェ', '温泉', 'リラックス'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd3',
    title: '河津桜まつり 早春ドライブ',
    summary: '一足早い春を感じに河津桜を見に行きませんか？見頃は2月中旬〜3月上旬。お子様も楽しめる屋台も充実。',
    imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&h=600&fit=crop',
    category: 'nature',
    source: 'AI提案',
    isRead: false,
    isNew: true,
    createdAt: '2026-02-12',
    season: 'spring',
    estimatedDriveTime: '約2時間',
    estimatedDistance: '約120km',
    details: '伊豆・河津町で毎年開催される河津桜まつりへのドライブプラン。約8000本の河津桜が川沿いに咲き誇る絶景は圧巻です。桜並木の下を散策しながら、地元グルメの屋台も楽しめます。帰りは伊豆の温泉に立ち寄って、早春のドライブを満喫しましょう。',
    tags: ['桜', '自然', 'イベント', '家族向け'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd4',
    title: '横浜みなとみらいイルミネーション',
    summary: '冬の横浜を彩る光の祭典。ディナークルーズとセットで特別な夜を過ごしませんか？',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&h=600&fit=crop',
    category: 'event',
    source: 'イベント情報',
    isRead: false,
    isNew: false,
    createdAt: '2026-02-10',
    season: 'winter',
    estimatedDriveTime: '約40分',
    estimatedDistance: '約25km',
    details: '横浜みなとみらいエリア一帯が美しいイルミネーションで彩られます。赤レンガ倉庫、ランドマークタワー周辺、山下公園など、各スポットで異なるテーマのライトアップを楽しめます。クルマなら効率よく複数スポットを巡ることができます。',
    tags: ['イルミネーション', 'デート', '夜景'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd5',
    title: '湘南T-SITE で過ごす休日',
    summary: '本とカフェと雑貨。知的好奇心を満たすおしゃれスポットで、ゆったりとした休日を。',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
    category: 'magazine',
    source: '提携メディア',
    sourceCredit: 'BRUTUS 2026年2月号',
    isRead: false,
    isNew: false,
    createdAt: '2026-02-08',
    season: 'all',
    estimatedDriveTime: '約50分',
    estimatedDistance: '約35km',
    details: '湘南エリアのカルチャースポット、湘南T-SITEでの休日プラン。蔦屋書店を中心に、こだわりのショップやレストランが集まる複合施設です。ブックカフェでゆっくり読書を楽しんだり、湘南の海を眺めながらランチをしたり。近くの片瀬海岸まで足を伸ばすのもおすすめです。',
    tags: ['カフェ', '読書', 'おしゃれ'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd6',
    title: 'ファミリーで楽しむ八景島シーパラダイス',
    summary: 'イルカショーに水族館、遊園地まで一日中遊べる！お子様の笑顔間違いなしのスポットです。',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
    category: 'family',
    source: 'AI提案',
    isRead: false,
    isNew: false,
    createdAt: '2026-02-06',
    season: 'all',
    estimatedDriveTime: '約45分',
    estimatedDistance: '約30km',
    details: '横浜・八景島シーパラダイスは、水族館・遊園地・レストラン・ショッピングモールが一体となったエンターテインメントスポット。お子様が大喜びのイルカショーや、ふれあいラグーンでの海の生き物との触れ合い体験など、家族みんなで楽しめるコンテンツが充実しています。駐車場も広々としていて安心です。',
    tags: ['水族館', '遊園地', '家族向け', 'お子様'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd7',
    title: '秩父・長瀞で渓谷ハイキング',
    summary: '四季折々の渓谷美を楽しむ日帰りトリップ。ライン下りと名物わらじカツ丼も外せません。',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
    category: 'nature',
    source: 'AI提案',
    isRead: false,
    isNew: false,
    createdAt: '2026-02-04',
    season: 'all',
    estimatedDriveTime: '約2時間',
    estimatedDistance: '約100km',
    details: '埼玉県の秩父・長瀞エリアを楽しむ日帰りドライブプラン。長瀞の岩畳でのハイキング、荒川のライン下り、秩父市内で名物のわらじカツ丼ランチを満喫できます。四季を通じて美しい渓谷の景色が楽しめ、特に紅葉シーズンは絶景です。',
    tags: ['ハイキング', '自然', 'グルメ', 'アクティブ'],
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'd8',
    title: '話題の映画「空と海の間」公開記念ドライブ',
    summary: 'ロケ地の湘南エリアを巡る聖地巡礼ドライブ。映画の世界観に浸る特別な体験を。',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=600&fit=crop',
    category: 'movie',
    source: '映画情報',
    isRead: false,
    isNew: false,
    createdAt: '2026-02-02',
    season: 'all',
    estimatedDriveTime: '約1時間',
    estimatedDistance: '約40km',
    details: '話題の映画「空と海の間」のロケ地を巡るドライブプラン。江ノ島、七里ヶ浜、鎌倉高校前踏切など、映画の名シーンが撮影されたスポットを巡ります。映画を観てから行くと感動もひとしお。カメラを持って出かけましょう。',
    tags: ['映画', '聖地巡礼', '湘南', '写真'],
    mapUrl: 'https://maps.google.com',
  },
];
